CREATE TABLE  "NS_USERS" 
   (	"USER_NO" NUMBER(6,0) NOT NULL ENABLE, 
	"ID" VARCHAR2(30), 
	"PASSWORD" VARCHAR2(30), 
	"NAME" VARCHAR2(50), 
	 CONSTRAINT "NS_USERS_PK" PRIMARY KEY ("USER_NO") ENABLE
   ) ;